// Generated by CoffeeScript 1.9.3
(function() {
  var handleCollapse, i, ident, len, ref;

  handleCollapse = function(ident) {
    return $('#' + ident + 'Button').click(function() {
      if ($(this).hasClass('fa-angle-down')) {
        $(this).removeClass('fa-angle-down');
        $(this).addClass('fa-angle-up');
        return $('#' + ident + 'Collapse').collapse('show');
      } else {
        $(this).removeClass('fa-angle-up');
        $(this).addClass('fa-angle-down');
        return $('#' + ident + 'Collapse').collapse('hide');
      }
    });
  };

  ref = ['grades', 'grades2', 'skills'];
  for (i = 0, len = ref.length; i < len; i++) {
    ident = ref[i];
    handleCollapse(ident);
  }

}).call(this);
