// Generated by CoffeeScript 1.12.2
(function() {
  var mkString, timeline;

  mkString = function(element, obj) {
    var i, len, results, s;
    if (obj.constructor.name === 'Array') {
      results = [];
      for (i = 0, len = obj.length; i < len; i++) {
        s = obj[i];
        element.append('span').text(s);
        results.push(element.append('br'));
      }
      return results;
    } else {
      return element.append('span').text(obj);
    }
  };

  timeline = d3.select('#career ul.timeline');

  d3.json("data/career.json", function(data) {
    var i, info, key, len, li, list, obj, panel, results, value;
    results = [];
    for (i = 0, len = data.length; i < len; i++) {
      obj = data[i];
      if ('milestone' in obj) {
        results.push(timeline.append('li').attr({
          "class": 'tldate'
        }).text(obj.milestone));
      } else {
        li = timeline.append('li');
        if ('$inverted' in obj) {
          li.attr({
            "class": 'timeline-inverted'
          });
        }
        li.append('div').attr({
          "class": 'tl-circ'
        });
        panel = li.append('div');
        panel.attr({
          "class": 'timeline-panel'
        });
        console.log(panel);
        panel.append('div').attr({
          "class": 'tl-heading'
        }).append('h4').text(obj['$title']);
        list = panel.append('ul');
        list.attr({
          "class": 'tl-body'
        });
        results.push((function() {
          var results1;
          results1 = [];
          for (key in obj) {
            value = obj[key];
            info = list.append('li');
            if (key === '$time') {
              info.append('i').attr({
                "class": 'glyphicon glyphicon-time'
              });
              info.append('br');
              info.append('span').text(obj['$time']);
              results1.push(info.append('br'));
            } else if (key === '$place') {
              info.append('i').attr({
                "class": 'glyphicon glyphicon-map-marker'
              });
              info.append('br');
              mkString(info, obj['$place']);
              results1.push(info.append('br'));
            } else if (key === '$venue') {
              info.append('i').attr({
                "class": 'glyphicon glyphicon-home'
              });
              info.append('br');
              mkString(info, obj['$venue']);
              results1.push(info.append('br'));
            } else if (key !== '$title' && key !== '$inverted') {
              info.append('span').attr({
                "class": 'emph'
              }).text(key);
              info.append('br');
              mkString(info, obj[key]);
              results1.push(info.append('br'));
            } else {
              results1.push(console.log('skip'));
            }
          }
          return results1;
        })());
      }
    }
    return results;
  });

}).call(this);
