// Generated by CoffeeScript 1.12.1
(function() {
  var timeline;

  timeline = d3.select('#career ul.timeline');

  d3.json("data/career.json", function(data) {
    var i, info, key, len, li, list, obj, panel, results, value;
    results = [];
    for (i = 0, len = data.length; i < len; i++) {
      obj = data[i];
      if ('milestone' in obj) {
        results.push(timeline.append('li').attr({
          "class": 'tldate'
        }).text(obj.milestone));
      } else {
        li = timeline.append('li');
        if ('$inverted' in obj) {
          li.attr({
            "class": 'timeline-inverted'
          });
        }
        li.append('div').attr({
          "class": 'tl-circ'
        });
        panel = li.append('div');
        panel.attr({
          "class": 'timeline-panel'
        });
        console.log(panel);
        panel.append('div').attr({
          "class": 'tl-heading'
        }).append('h4').text(obj['$title']);
        list = panel.append('ul');
        list.attr({
          "class": 'tl-body'
        });
        results.push((function() {
          var results1;
          results1 = [];
          for (key in obj) {
            value = obj[key];
            info = list.append('li');
            if (key === '$time') {
              list.append('i').attr({
                "class": 'glyphicon glyphicon-time'
              }).append('br');
              results1.push(list.text(obj['$time']));
            } else if (key === '$place') {
              results1.push(console.log('place'));
            } else if (key === '$venue') {
              results1.push(console.log('venue'));
            } else if (key === '$title' || key === '$inverted') {
              results1.push(console.log('skip'));
            } else {
              results1.push(console.log('custom'));
            }
          }
          return results1;
        })());
      }
    }
    return results;
  });

}).call(this);
