// Generated by CoffeeScript 1.9.3
(function() {
  var publicationEntry;

  publicationEntry = function(json) {
    if (json.venueAbr == null) {
      json.venueAbr = "DRAFT";
    }
    if (json.venue == null) {
      json.venue = "";
    }
    return " <dt> " + json.venueAbr + "\n      " + (json.$draft != null ? "<br><div class=wip>UNDER<br>SUBMISSION</div>" : "") + "\n </dt>\n <dd>\n   <span class=\"paperTitle\"> " + json.title + "</span>\n   <a href=\"data/publications/" + json.id + ".pdf\" target='_blank'> <i class='fa fa-book'></i> </a>\n   <br> <span class=\"paperAuthors\"> " + json.authors + "</span>\n   <br> <span class=\"paperVenue\"> " + json.venue + "\n</span>\n </dd>";
  };

  d3.json("data/publications.json", function(pubs) {
    var pub;
    return $('#publicationsTable').append((function() {
      var i, len, results;
      results = [];
      for (i = 0, len = pubs.length; i < len; i++) {
        pub = pubs[i];
        results.push(publicationEntry(pub));
      }
      return results;
    })());
  });

}).call(this);
