// Generated by CoffeeScript 1.12.2
(function() {
  var generateChart, i, len, ref, removeXLabel, skill;

  removeXLabel = function(chart) {
    return chart.svg().append('text').attr('class', 'x-axis-label').attr('text-anchor', 'middle').text('');
  };

  generateChart = function(skill) {
    return d3.csv("data/" + skill + ".csv", function(data) {
      var chart, grades, name, ndx;
      ndx = crossfilter(data);
      name = ndx.dimension(function(d) {
        return d.Name;
      });
      grades = name.group().reduceSum(function(d) {
        return d.Grade;
      });
      chart = dc.rowChart("#" + skill).width(500).height(40 * ndx.size()).x(d3.scale.ordinal()).elasticX(true).transitionDuration(2000).colorAccessor(function(d) {
        return d.value * .1;
      }).colors(["#ff0000", "#ff4400", "#ff8800", "#ffaa00", "#eeff00", "#aaff00", "#88ff22", "#44ff22", "#00ff22"]).dimension(name).group(grades);
      chart.xAxis().tickValues([]);
      chart.render();
      return removeXLabel(chart);
    });
  };

  ref = ['languages', 'frameworks', 'typesetting', 'webdev'];
  for (i = 0, len = ref.length; i < len; i++) {
    skill = ref[i];
    generateChart(skill);
  }

}).call(this);
