# Use new container infrastructure to enable caching
sudo: false

language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - nodejs

install:
# Stack
- curl -sSL https://get.haskellstack.org/ | sh
- stack --version
# CoffeeScript
- npm install -g coffee-script@1.9.3

script:
- make build

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: hakyll
  target_branch: master
  local_dir: ./_site
